services:
  postgres:
    image: postgres:15
    container_name: inno-microservices
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  liquibase:
    image: liquibase/liquibase:4.29
    container_name: liquibase
    depends_on:
      - postgres
    working_dir: /liquibase
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: >
      update
      --url=jdbc:postgresql://postgres:5432/mydb
      --username=root
      --password=1111
      --changeLogFile=changelog/db.changelog-master.xml

volumes:
  postgres_data: